from typing import List
from .. import BaseOperator


def generate_vsm(operator: BaseOperator) -> List[str]:
    operator.check_layout_in("((8_L2B:1, 32:1), (8_MAB:2, 8_L1B:1, 2_MAB:1, 4_PE:1, 2_W:1))", 0)
    operator.check_layout_in("((16:1), (8_MAB:2, 8_L1B:1, 2_MAB:1, 4_PE:1, 2_W:1))", 1)
    operator.check_layout_out("((4_L2B:2, 64:8), (8:1, 2_W:1))")
    assert operator.loc_prefix_out() == "d" # DRAM 出力


    assert operator.loc_prefix_in(0) == "m" # LM0 に入力0を仮定し、実装を軽減
    assert operator.loc_prefix_in(1) == "m" # LM0 に入力1を仮定し、実装を軽減
    
    assert operator.addr_in(0) == 0   # 入力1 を addr0 に仮定し、実装を軽減
                                            # ↑、つまり、入力 0 が "$lm0v" だと仮定している
    assert operator.addr_in(1) == operator.memory_len_in(0)
                                            # 入力2 を、入力 0 の直後と仮定し、実装を軽減


    c = operator.addr_out()      # "$d0" の "0" の部分
    
    # test unit_tests/train_step/Gemm_256x1024_16x1024_256x16_transB_a/
    # 問題名：「Mmul TB D 256_1024_16」
    
    lines = []

    lines.append("gbfn $lm0v $lr0v")
    lines.append("gbfn $lm8v $lr8v")
    lines.append("gbfn $lm16v $lr16v")
    lines.append("gbfn $lm24v $lr24v")
    lines.append("gbfn $lm32v $lr32v")
    lines.append("gbfn $lm40v $lr40v")
    lines.append("gbfn $lm48v $lr48v")
    lines.append("gbfn $lm56v $lr56v")
    lines.append("")
    lines.append("")
    lines.append("gbfn    $lm64v  $nowrite")
    lines.append("gmwrite $aluf $ly0")
    lines.append("gbfn    $lm72v $nowrite")
    lines.append("gmwrite $aluf $ly4")
    lines.append("gmmul $ly $lr0v $ln0v4")
    lines.append("")
    lines.append("gbfn    $lm80v  $nowrite")
    lines.append("gmwrite $aluf $ly0")
    lines.append("gbfn    $lm88v $nowrite")
    lines.append("gmwrite $aluf $ly4")
    lines.append("gmmul $ly $lr0v $ln2v4")
    lines.append("")
    lines.append("")
    lines.append("gbfn    $lm64v  $nowrite")
    lines.append("gmwrite $aluf $ly0")
    lines.append("gbfn    $lm72v $nowrite")
    lines.append("gmwrite $aluf $ly4")
    lines.append("gmmul $ly $lr8v $ln16v4")
    lines.append("")
    lines.append("gbfn    $lm80v  $nowrite")
    lines.append("gmwrite $aluf $ly0")
    lines.append("gbfn    $lm88v $nowrite")
    lines.append("gmwrite $aluf $ly4")
    lines.append("gmmul $ly $lr8v $ln18v4")
    lines.append("")
    lines.append("")
    lines.append("gbfn    $lm64v  $nowrite")
    lines.append("gmwrite $aluf $ly0")
    lines.append("gbfn    $lm72v $nowrite")
    lines.append("gmwrite $aluf $ly4")
    lines.append("gmmul $ly $lr16v $ln32v4")
    lines.append("")
    lines.append("gbfn    $lm80v  $nowrite")
    lines.append("gmwrite $aluf $ly0")
    lines.append("gbfn    $lm88v $nowrite")
    lines.append("gmwrite $aluf $ly4")
    lines.append("gmmul $ly $lr16v $ln34v4")
    lines.append("")
    lines.append("")
    lines.append("gbfn    $lm64v  $nowrite")
    lines.append("gmwrite $aluf $ly0")
    lines.append("gbfn    $lm72v $nowrite")
    lines.append("gmwrite $aluf $ly4")
    lines.append("gmmul $ly $lr24v $ln48v4")
    lines.append("")
    lines.append("gbfn    $lm80v  $nowrite")
    lines.append("gmwrite $aluf $ly0")
    lines.append("gbfn    $lm88v $nowrite")
    lines.append("gmwrite $aluf $ly4")
    lines.append("gmmul $ly $lr24v $ln50v4")
    lines.append("")
    lines.append("")
    lines.append("gbfn    $lm64v  $nowrite")
    lines.append("gmwrite $aluf $ly0")
    lines.append("gbfn    $lm72v $nowrite")
    lines.append("gmwrite $aluf $ly4")
    lines.append("gmmul $ly $lr32v $ln64v4")
    lines.append("")
    lines.append("gbfn    $lm80v  $nowrite")
    lines.append("gmwrite $aluf $ly0")
    lines.append("gbfn    $lm88v $nowrite")
    lines.append("gmwrite $aluf $ly4")
    lines.append("gmmul $ly $lr32v $ln66v4")
    lines.append("")
    lines.append("")
    lines.append("gbfn    $lm64v  $nowrite")
    lines.append("gmwrite $aluf $ly0")
    lines.append("gbfn    $lm72v $nowrite")
    lines.append("gmwrite $aluf $ly4")
    lines.append("gmmul $ly $lr40v $ln80v4")
    lines.append("")
    lines.append("gbfn    $lm80v  $nowrite")
    lines.append("gmwrite $aluf $ly0")
    lines.append("gbfn    $lm88v $nowrite")
    lines.append("gmwrite $aluf $ly4")
    lines.append("gmmul $ly $lr40v $ln82v4")
    lines.append("")
    lines.append("")
    lines.append("gbfn    $lm64v  $nowrite")
    lines.append("gmwrite $aluf $ly0")
    lines.append("gbfn    $lm72v $nowrite")
    lines.append("gmwrite $aluf $ly4")
    lines.append("gmmul $ly $lr48v $ln96v4")
    lines.append("")
    lines.append("gbfn    $lm80v  $nowrite")
    lines.append("gmwrite $aluf $ly0")
    lines.append("gbfn    $lm88v $nowrite")
    lines.append("gmwrite $aluf $ly4")
    lines.append("gmmul $ly $lr48v $ln98v4")
    lines.append("")
    lines.append("")
    lines.append("gbfn    $lm64v  $nowrite")
    lines.append("gmwrite $aluf $ly0")
    lines.append("gbfn    $lm72v $nowrite")
    lines.append("gmwrite $aluf $ly4")
    lines.append("gmmul $ly $lr56v $ln112v4")
    lines.append("")
    lines.append("gbfn    $lm80v  $nowrite")
    lines.append("gmwrite $aluf $ly0")
    lines.append("gbfn    $lm88v $nowrite")
    lines.append("gmwrite $aluf $ly4")
    lines.append("gmmul $ly $lr56v $ln114v4")
    lines.append("")
    lines.append("")
    lines.append("nop/2")
    lines.append("l1bmrffadd $lln0v  $llb0")
    lines.append("l1bmrffadd $lln16v $llb32")
    lines.append("l1bmrffadd $lln32v $llb64")
    lines.append("l1bmrffadd $lln48v $llb96")
    lines.append("l1bmrffadd $lln64v $llb128")
    lines.append("l1bmrffadd $lln80v $llb160")
    lines.append("l1bmrffadd $lln96v $llb192")
    lines.append("l1bmrffadd $lln112v $llb224")
    lines.append("")
    lines.append("")
    lines.append("l2bmrffadd $lb0  $lc0")
    lines.append("l2bmrffadd $lb64 $lc64")
    lines.append("l2bmrffadd $lb128 $lc128")
    lines.append("l2bmrffadd $lb192 $lc192")
    lines.append("")
    lines.append("nop")
    lines.append(f"mvp/n256 $lc0@.0 $d{c}")
    lines.append(f"mvp/n256 $lc0@.1 $d{c+256}")

    return lines