from typing import List
from .. import BaseOperator



def generate_vsm(operator: BaseOperator) -> List[str]:
    operator.check_layout_in("((8_L2B:1, 32:2), (2:1, 4_PE:1, 2_W:1))", 0)
    operator.check_layout_in("((8_L2B:1, 32:1), (8_MAB:2, 8_L1B:1, 2_MAB:1, 4_PE:1, 2_W:1))", 1)
    operator.check_layout_out("((4_L2B:2, 4:512), (512:1, 2_W:1))")
    assert operator.loc_prefix_out() == "d" # DRAM 出力


    assert operator.loc_prefix_in(0) == "m" # LM0 に入力を仮定し、実装を軽減
    assert operator.loc_prefix_in(1) == "m" # LM0 に入力を仮定し、実装を軽減
    
    assert operator.addr_in(0) == 0   # 入力1 を addr0 に仮定し、実装を軽減
                                           # ↑、つまり、入力 0 が "$lm0v" だと仮定している
    assert operator.addr_in(1) == operator.memory_len_in(0)
                                            # 入力2 を、入力 0 の直後と仮定し、実装を軽減


    c = operator.addr_out()      # "$d0" の "0" の部分

    # test unit_tests/train_step/Gemm_256x16_256x16_16x16_transA_a/
    # 問題名： 「Mmul TA D 16_256_1024」
    
    lines = []
    lines.append(f"gmwrite $lm0v4 $ly0")
    lines.append(f"gmwrite $lm16v4 $ly4")
    lines.append(f"gmread $ly0 $nowrite")
    lines.append(f"gbfn $mreadf $lr0v4")
    lines.append(f"gmread $ly4 $nowrite")
    lines.append(f"gbfn $mreadf $lr16v4")
    lines.append(f"")
    lines.append(f"# A01")
    lines.append(f"gmwrite $lm2v4 $ly0")
    lines.append(f"gmwrite $lm18v4 $ly4")
    lines.append(f"gmread $ly0 $nowrite")
    lines.append(f"gbfn $mreadf $lr2v4")
    lines.append(f"gmread $ly4 $nowrite")
    lines.append(f"gbfn $mreadf $lr18v4")
    lines.append(f"")
    lines.append(f"# A10")
    lines.append(f"gmwrite $lm32v4  $ly0")
    lines.append(f"gmwrite $lm48v4 $ly4")
    lines.append(f"gmread $ly0  $nowrite")
    lines.append(f"gbfn $mreadf  $lr32v4")
    lines.append(f"gmread $ly4  $nowrite")
    lines.append(f"gbfn $mreadf $lr48v4")
    lines.append(f"")
    lines.append(f"# A11")
    lines.append(f"gmwrite $lm34v4  $ly0")
    lines.append(f"gmwrite $lm50v4 $ly4")
    lines.append(f"gmread $ly0  $nowrite")
    lines.append(f"gbfn $mreadf  $lr34v4")
    lines.append(f"gmread $ly4  $nowrite")
    lines.append(f"gbfn $mreadf $lr50v4")
    lines.append(f"")
    lines.append(f"# A20")
    lines.append(f"gmwrite $lm64v4 $ly0")
    lines.append(f"gmwrite $lm80v4 $ly4")
    lines.append(f"gmread  $ly0 $nowrite")
    lines.append(f"gbfn $mreadf $lr64v4")
    lines.append(f"gmread  $ly4 $nowrite")
    lines.append(f"gbfn $mreadf $lr80v4")
    lines.append(f"")
    lines.append(f"# A21")
    lines.append(f"gmwrite $lm66v4 $ly0")
    lines.append(f"gmwrite $lm82v4 $ly4")
    lines.append(f"gmread  $ly0 $nowrite")
    lines.append(f"gbfn $mreadf $lr66v4")
    lines.append(f"gmread  $ly4 $nowrite")
    lines.append(f"gbfn $mreadf $lr82v4")
    lines.append(f"")
    lines.append(f"# A30")
    lines.append(f"gmwrite $lm96v4 $ly0")
    lines.append(f"gmwrite $lm112v4 $ly4")
    lines.append(f"gmread  $ly0 $nowrite")
    lines.append(f"gbfn $mreadf $lr96v4")
    lines.append(f"gmread  $ly4 $nowrite")
    lines.append(f"gbfn $mreadf $lr112v4")
    lines.append(f"")
    lines.append(f"# A31")
    lines.append(f"gmwrite $lm98v4 $ly0")
    lines.append(f"gmwrite $lm114v4 $ly4")
    lines.append(f"gmread  $ly0 $nowrite")
    lines.append(f"gbfn $mreadf $lr98v4")
    lines.append(f"gmread  $ly4 $nowrite")
    lines.append(f"gbfn $mreadf $lr114v4")
    lines.append(f"")
    lines.append(f"####################################")
    lines.append(f"####################################")
    lines.append(f"# B0")
    lines.append(f"gmwrite  $lm128v  $lx0")
    lines.append(f"gmwrite  $lm136v  $lx4")
    lines.append(f"gmread $lx0 $nowrite")
    lines.append(f"gbfn  $mreadf  $ls100v")
    lines.append(f"gmread $lx4 $nowrite")
    lines.append(f"gbfn  $mreadf  $ls108v")
    lines.append(f"")
    lines.append(f"")
    lines.append(f"# A00,01")
    lines.append(f"gmwrite $ls100v $lx0")
    lines.append(f"gmwrite $ls108v $lx4")
    lines.append(f"gmmul $lx $lr0v4  $ls0v")
    lines.append(f"gmmul $lx $lr16v4 $ls8v")
    lines.append(f"gmmul $lx $lr2v4  $ls16v")
    lines.append(f"gmmul $lx $lr18v4 $ls24v")
    lines.append(f"")
    lines.append(f"##############################")
    lines.append(f"# B1")
    lines.append(f"gmwrite  $lm144v  $lx0")
    lines.append(f"gmwrite  $lm152v  $lx4")
    lines.append(f"gmread $lx0 $nowrite")
    lines.append(f"gbfn  $mreadf  $ls100v")
    lines.append(f"gmread $lx4 $nowrite")
    lines.append(f"gbfn  $mreadf  $ls108v")
    lines.append(f"")
    lines.append(f"")
    lines.append(f"# A10,11")
    lines.append(f"gmwrite $ls100v $lx0")
    lines.append(f"gmwrite $ls108v $lx4")
    lines.append(f"gmfma $lx $lr32v4 $ls0v  $ls0v")
    lines.append(f"gmfma $lx $lr48v4 $ls8v  $ls8v")
    lines.append(f"gmfma $lx $lr34v4 $ls16v $ls16v")
    lines.append(f"gmfma $lx $lr50v4 $ls24v $ls24v")
    lines.append(f"")
    lines.append(f"##############################")
    lines.append(f"# B2")
    lines.append(f"gmwrite  $lm160v  $lx0")
    lines.append(f"gmwrite  $lm168v  $lx4")
    lines.append(f"gmread $lx0 $nowrite")
    lines.append(f"gbfn  $mreadf  $ls100v")
    lines.append(f"gmread $lx4 $nowrite")
    lines.append(f"gbfn  $mreadf  $ls108v")
    lines.append(f"")
    lines.append(f"")
    lines.append(f"# A20,21")
    lines.append(f"gmwrite $ls100v $lx0")
    lines.append(f"gmwrite $ls108v $lx4")
    lines.append(f"gmfma $lx $lr64v4 $ls0v  $ls0v")
    lines.append(f"gmfma $lx $lr80v4 $ls8v  $ls8v")
    lines.append(f"gmfma $lx $lr66v4 $ls16v $ls16v")
    lines.append(f"gmfma $lx $lr82v4 $ls24v $ls24v")
    lines.append(f"")
    lines.append(f"##############################")
    lines.append(f"# B3")
    lines.append(f"gmwrite  $lm176v  $lx0")
    lines.append(f"gmwrite  $lm184v  $lx4")
    lines.append(f"gmread $lx0 $nowrite")
    lines.append(f"gbfn  $mreadf  $ls100v")
    lines.append(f"gmread $lx4 $nowrite")
    lines.append(f"gbfn  $mreadf  $ls108v")
    lines.append(f"")
    lines.append(f"")
    lines.append(f"# A30,31")
    lines.append(f"gmwrite $ls100v $lx0")
    lines.append(f"gmwrite $ls108v $lx4")
    lines.append(f"gmfma $lx $lr96v4  $ls0v  $ln0v")
    lines.append(f"gmfma $lx $lr112v4 $ls8v  $ln8v")
    lines.append(f"gmfma $lx $lr98v4  $ls16v $ln16v")
    lines.append(f"gmfma $lx $lr114v4 $ls24v $ln24v")
    lines.append(f"")
    lines.append(f"nop/2")
    lines.append(f"##############################")
    lines.append(f"# PE: ((16:1), (4_PE:1, 2_W:1)) : $ln[0:32]")
    lines.append(f"")
    lines.append(f"l1bmd $ln0v $lb0")
    lines.append(f"l1bmd $ln8v $lb256")
    lines.append(f"l1bmd $ln16v $lb512")
    lines.append(f"l1bmd $ln24v $lb768")
    lines.append(f"")
    lines.append(f"l2bmd $lb0 $lc0")
    lines.append(f"l2bmd $lb32 $lc256")
    lines.append(f"l2bmd $lb64 $lc512")
    lines.append(f"l2bmd $lb96 $lc768")
    lines.append(f"l2bmd $lb128 $lc1024")
    lines.append(f"l2bmd $lb160 $lc1280")
    lines.append(f"l2bmd $lb192 $lc1536")
    lines.append(f"l2bmd $lb224 $lc1792")
    lines.append(f"l2bmd $lb256 $lc2048")
    lines.append(f"l2bmd $lb288 $lc2304")
    lines.append(f"l2bmd $lb320 $lc2560")
    lines.append(f"l2bmd $lb352 $lc2816")
    lines.append(f"l2bmd $lb384 $lc3072")
    lines.append(f"l2bmd $lb416 $lc3328")
    lines.append(f"l2bmd $lb448 $lc3584")
    lines.append(f"l2bmd $lb480 $lc3840")
    lines.append(f"l2bmd $lb512 $lc4096")
    lines.append(f"l2bmd $lb544 $lc4352")
    lines.append(f"l2bmd $lb576 $lc4608")
    lines.append(f"l2bmd $lb608 $lc4864")
    lines.append(f"l2bmd $lb640 $lc5120")
    lines.append(f"l2bmd $lb672 $lc5376")
    lines.append(f"l2bmd $lb704 $lc5632")
    lines.append(f"l2bmd $lb736 $lc5888")
    lines.append(f"l2bmd $lb768 $lc6144")
    lines.append(f"l2bmd $lb800 $lc6400")
    lines.append(f"l2bmd $lb832 $lc6656")
    lines.append(f"l2bmd $lb864 $lc6912")
    lines.append(f"l2bmd $lb896 $lc7168")
    lines.append(f"l2bmd $lb928 $lc7424")
    lines.append(f"l2bmd $lb960 $lc7680")
    lines.append(f"l2bmd $lb992 $lc7936")
    lines.append(f"nop")
    lines.append(f"mvrffadd/n8192 $lc0 $p0@0")
    lines.append(f"mvp/n2048 $p0@0    $d{c}@0")
    lines.append(f"mvp/n2048 $p2048@0 $d{c}@1")
    lines.append(f"mvp/n2048 $p4096@0 $d{c}@2")
    lines.append(f"mvp/n2048 $p6144@0 $d{c}@3")

    return lines